### ISSUE TITLE
Use of wildcard domain name

### ISSUE THREAD

**Issue by duncan9562** [analbeard/memset_dns_update#1]
It doesn't look like the use of wildcard domain names is currently supported. This could well be a limitation in the Memset API, however this is untested.

Example:-
I have an A record set up for *.mydomain.com in the Memset DNS manager which works perfectly.

If I use the DNS updater script as follows:-
`/root/memset_dns_update/dns_update.py -s *.mydomain.com -a <api_key>`

...I get the following exception raised:-
`Traceback (most recent call last):
  File "/root/memset_dns_update/dns_update.py", line 172, in <module>
    main = Main()
  File "/root/memset_dns_update/dns_update.py", line 54, in __init__
    raise Exception
Exception`

**Comment by analbeard** [comment]
This should be fixed by 29d7912c4775 - can you pull and give it a try?

**Comment by duncan9562** [comment]
Works perfectly - thanks for the quick turnaround!
